# Import the 'webdriver' and 'time' modules from Selenium and Python
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys 
from selenium.webdriver.support import expected_conditions as EC
print("Drivers have been successfully loaded.")

# Instantiate a Chrome 'webdriver' object by specifying the path to the Chrome driver executable file
driver = webdriver.Chrome("executable_path=C:\Drivers\chromedriver.exe")
print("Drivers have been successfully loaded.")

# Navigate to the web page specified in the URL using the 'get' method on the 'driver' object
driver.get("https://the-internet.herokuapp.com/checkboxes")
print("Web page has been successfully loaded.")

# Maximize the window
driver.maximize_window()
print("Window has been maximized.")

# Implicitly wait for 10 seconds for the page to load
driver.implicitly_wait(10)
print("Implicitly waiting for 10 seconds for the page to load.")

# Time delay for the execution of each task
t = .1

# Locate the checkbox buttons and store them in variables
print("Locating checkbox buttons and storing them in variables.")
checkbox1 = driver.find_element(By.XPATH, "(//input[@type='checkbox'])[1]")
checkbox2 = driver.find_element(By.XPATH, "(//input[@type='checkbox'])[2]")

# Wait for 0.1 seconds
print("Waiting for .1 seconds")
time.sleep(t)

# Check if checkbox 1 is selected and, if so, click it to deselect it
if checkbox1.is_selected():
    checkbox1.click()
    print("Button 1 has been deselected.")
    time.sleep(t)

# Check if checkbox 2 is selected and, if so, click it to deselect it
if checkbox2.is_selected():
    checkbox2.click()
    print("Button 2 has been deselected.")
    time.sleep(t)

# Click on checkbox 1 to select it
checkbox1.click()
print("Button 1 has been selected.")

# Wait for 0.1 seconds
time.sleep(t)

# Click on checkbox 1 to deselect it
checkbox1.click()
print("Button 1 has been deselected.")
time.sleep(t)

# Click on checkbox 2 to select it
checkbox2.click()
print("Button 2 has been selected.")

# Wait for 0.1 seconds
time.sleep(t)

# Click on checkbox 2 to deselect it
checkbox2.click()
print("Button 2 has been deselected.")
time.sleep(t)

# Wait for 0.1 seconds
print("Waiting for 0.1 seconds.")
time.sleep(t)

# Print a message on the screen to indicate that button 2 has been selected
print("Button 2 has been selected.")
time.sleep(t)

# Close the browser window using the 'close' method on the object
driver.close()

print("The test has been successful. The window and drivers have been closed.")

print("This was a test generated by software development engineer Pierre Grandett - Develups.")