# Import the 'webdriver' and 'time' modules from Selenium and Python
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys 
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import TimeoutException
print("Drivers have been successfully loaded.")

# Instantiate a Chrome 'webdriver' object by specifying the path to the Chrome driver executable file
driver = webdriver.Chrome("executable_path=C:\Drivers\chromedriver.exe")

print("Drivers have been successfully loaded.")

# Navigate to the web page specified in the URL using the 'get' method on the 'driver' object
driver.get("https://pixabay.com/es/")
print("Web page has been successfully loaded.")

# Maximize the window
driver.maximize_window()
print("Window has been maximized.")
# Time delay for the execution of each task
t = 1
print("Locate if the element exists")

#driver.execute_script("window.scrollTo(0,2000)")
#day = WebDriverWait(driver,10).until(EC.visibility_of_element_located((By.ID, "//select[contains(@id,'wsf-1-field-53')]")))#
# "First block

try:
   buscar=WebDriverWait(driver,5).until(EC.visibility_of_element_located((By.XPATH, "//span[@class='label--Ngqjq'][contains(.,'Descubre más')]")))
   buscar=driver.find_element(By.XPATH,"//span[@class='label--Ngqjq'][contains(.,'Descubre más')]")
   ir = driver.execute_script("arguments[0].scrollIntoView();",buscar)
   time.sleep(t)
   #buscar = driver.find_element(By.XPATH, "//span[@class='label--Ngqjq'][contains(.,'Descubre más')]").click()
   #time.sleep(t)
except TimeoutException as ex:
    print(ex.msg)
    print("the element its not avaible")
    time.sleep(t)
# "First block


# Close the browser window using the 'close' method on the object

driver.close()
print("The test has been successful. The window and drivers have been closed.")
print("This was a test generated by software development engineer Pierre Grandett - Develups.")
